
---
output: html_document
editor_options: 
  chunk_output_type: console
---

###Set up data analysis models for MplusAutomation

```{r data.analyses.setup}
#################################################################################
#####Self-made analyses: Detailed for Information Criteria Comparisons etc.######
#################################################################################
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
setwd("./LPGMLM_simus/")

LPGMLM_analysis <- '

[[init]]
iterators = n dat p;
n = 250 260 270 280 290 300 310 320 330 340 350 360 370 380 390 400 410 420 430 440 450 460 470 480 490 500
510 520 530 540 550 560 570 580 590 600 610 620 630 640 650 660 670 680 690 700 710 720 730 740 750;
dat = 1:100;
p = 4:6;

filename = "LPGMLM_analysis_[[n]]_[[dat]]_[[p]].inp";
outputDirectory = "D:/12 R projects/PRISMA/LPGMLM_simus/LPGMLM_analysis_inputs/n_[[n]]/";

[[/init]]

TITLE:
MMLPA_analysis_[[n]]_[[dat]]_[[p]]

DATA:
FILE IS
"D:/12 R projects/PRISMA/LPGMLM_simus/MMLPA_simus_inputs/n_[[n]]/
MMLPA_sim_[[n]]_[[dat]].dat";

VARIABLE:

NAMES = 
y1-y8
p
pattern
;

USEVARIABLES ARE
y1-y8
;

AUXILIARY = p;

CLASSES = p([[p]]);

MISSING = all(999.000000) all(999);

ANALYSIS:

TYPE = mixture;
STARTS 400 100;
PROCESS = 4 1;

MODEL:

%overall%

%p#1%

[y1-y8*];
y1-y8*;

%p#2%

[y1-y8*];
y1-y8*;

%p#3%

[y1-y8*];
y1-y8*;

%p#4%

[y1-y8*];
y1-y8*;

[[p > 4]]

%p#5%

[y1-y8*];
y1-y8*;

[[/p > 4]]

[[p > 5]]

%p#6%

[y1-y8*];
y1-y8*;

[[/p > 5]]

OUTPUT: sampstat tech11 tech14;
!Only for solution with 5 profiles and only if necessary
!SAVEDATA:
!FILE = cprobs_[[n]]_[[dat]]_[[p]]profiles.pro;
!SAVE = cprobabilities;

'

```

###Run analyses of simulated data

```{r run.dataanalyses}
library(MplusAutomation)
library(tidyverse)
#Write template into textfile
write(LPGMLM_analysis, file = "LPGMLM_analysis.txt")

#Write Mplus input files based on template for all 30 combinations of N, E, missingdata(attrition).
createModels("LPGMLM_analysis.txt")

#Run Mplus input files
setwd("D:/12 R projects/PRISMA/LPGMLM_simus/LPGMLM_analysis_inputs")
runModels(recursive = TRUE)

```

