---
output: html_document
editor_options: 
  chunk_output_type: console
---

###Set up data analysis models for MplusAutomation

```{r data.analyses.setup}
#################################################################################
#####Self-made analyses: Detailed for Information Criteria Comparisons etc.######
#################################################################################
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
setwd("./LPA_analysis_inputs/")

LPA_analysis <- '

[[init]]
iterators = n mis dat p;
n = 100 250 500 750 1000;
mis = 1 2 3 4;
dat = 1:3;
p = 4:6;

MissingNames#mis = "noattrition" "attrition05" "attrition10" "attrition15";

filename = "LPA_analysis_[[n]]_[[MissingNames#mis]]_[[dat]]_[[p]].inp";
outputDirectory = "C:/local user data/LPA_simus/LPA_analysis_inputs/n_[[n]]/[[MissingNames#mis]]/";

[[/init]]

TITLE:
LPA_analysis_[[n]]_[[MissingNames#mis]]_[[dat]]_[[p]]

DATA:
FILE IS
"C:/local user data/LPA_simus/LPA_simus_inputs/n_[[n]]/
[[MissingNames#mis]]/LPA_sim_[[n]]_[[MissingNames#mis]][[dat]].dat";

VARIABLE:

[[mis = 1]]

NAMES = 
y1-y8
p
;

[[/mis = 1]]

[[mis != 1]]

NAMES = 
y1-y8
p
pattern
;

[[/mis != 1]]

USEVARIABLES ARE
y1-y8
;

AUXILIARY = p;

CLASSES = p([[p]]);

MISSING = all(999.000000) all(999);

ANALYSIS:

TYPE = mixture;
STARTS 400 100;
PROCESS = 4 1;

MODEL:

%overall%

%p#1%

[y1-y8*];
y1-y8*;

%p#2%

[y1-y8*];
y1-y8*;

%p#3%

[y1-y8*];
y1-y8*;

%p#4%

[y1-y8*];
y1-y8*;

[[p > 4]]

%p#5%

[y1-y8*];
y1-y8*;

[[/p > 4]]

[[p > 5]]

%p#6%

[y1-y8*];
y1-y8*;

[[/p > 5]]

OUTPUT: sampstat tech11 tech14;
!Only for solution with 5 profiles and only if necessary
!SAVEDATA:
!FILE = cprobs_[[n]]_[[MissingNames#mis]][[dat]]_[[p]]profiles.pro;
!SAVE = cprobabilities;

'

```

###Run analyses of simulated data

```{r run.dataanalyses}
library(MplusAutomation)
install.packages("tidyverse")
#Write template into textfile
write(LPA_analysis, file = "LPA_analysis.txt")

#Write Mplus input files based on template for all 30 combinations of N, E, missingdata(attrition).
createModels("LPA_analysis.txt")

#Run Mplus input files
setwd("C:/local user data/LPA_simus/LPA_analysis_inputs/n_1000/")
runModels(recursive = TRUE)

```

